version: '2'

services:

    client:
        build: src/client
        image: client
        networks:
            - overlay
        environment: 
            - IN_DOCKER="InDocker"

    server:
        build: src/server
        image: server
        networks:
            - overlay

networks:
  overlay: